### ISSUE TITLE
Deal with previous version link?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/spec-generator#1]
I assume most spec generators (and at least ReSpec) will want to set the previous link at the time where the document is generated; now that could be set in the document's configuration, but that requires updating it each time a publication occurs, which is not ideal.

Could we instead provide that parameter automagically to the various generators, by reading data from a machine readable version of TR?

**Comment by darobin** [comment]
I believe this is now addressed!

**Comment by dontcallmedom** [comment]
(for reference, the "addressed"  above is alluding to 9555c9692d3f3318bf2da9fd79cdb5b0f38bf18c )

**Comment by dontcallmedom** [comment]
I'm not sure it addresses the issue — I think the responsibility of determining what prevMaturity and prevPublishDate are falls upon us (by parsing tr.rdf or maybe specrefs if we trust it enough for that)

**Comment by darobin** [comment]
Hmmmm. That can be done, but it somehow feels like it is breaking modularity. Do we expect the generator to be only used by Echidna? In that case I guess it doesn't matter. But if it is more open I would expect the caller to specify parts it wants to enforce/override and the generator to be as dumb as possible.

(Note: I would *definitely* want to trust specref on this, if only so I don't need to parse tr.rdf. Also, it's an incentive to publish data that specref can use and keep it up to date :)

**Comment by dontcallmedom** [comment]
Here is my thinking:
* we know we need the data
* we can't use this with Echidna without it
* it seems extremely unlikely Echidna could be made to send the data (at least in the short term)

So I think it's probably best to implement it in there, maybe as a temporary measure while we figure a better modularity.

Another option would be to add a parameter to respec to have it automagically set the previous publish date and maturity (e.g. prevPublishDate=auto).

On specref vs tr.rdf, I understand the pain of parsing RDF in JavaScript, but there is at least one case where I don't think specref has enough data for us: if a document is published more than once in a given day, and if the specref database has been updated in between the two publications, we need the previous publication date to be set to the previous dated version, not to latest one (which would otherwise create a circular reference).

(that edge case also makes it probably a bit more tricky to push this particular problem to respec, I think)

**Comment by darobin** [comment]
Ok, I hear your thinking. More than any other consideration I think that "it seems extremely unlikely Echidna could be made to send the data (at least in the short term)" is the most convincing one. Even if it were the worst architectural decision ever, the damn thing as a whole still needs to work :)

My reluctance to parse `tr.rdf` is largely due to the fact that I have very little bandwidth to devote to this right now, so unless someone else picks it up we're looking at a potentially lengthy delay.

I think that specref can be okay if it can give us the full list of versions for a given spec (I forget if the API supports that). From that we can just iterate backwards until we find a version that isn't dated today. Or am I missing something?

**Comment by dontcallmedom** [comment]
specref doesn't manage the version history: it has some versions of some specs when required by specific usage, but it doesn't try to collect spec history in general.

(note that @deniak tells me that the official mapping of tr.rdf in JSON is in progress, but I don't think we can wait for it in our timeline)

I'll take a stab at it.

**Comment by darobin** [comment]
Right, so specref does not currently expose the information — but it has it! The information is there precisely so that dated references can work. Exposing an option in its HTTP API so that it would return the full history for a spec would not be a huge amount of work. I think it might be the simplest thing in this case; I mean it has already solved the problem of converting the data in the first place.

If that doesn't work, I just realised that it probably has code to handle tr.rdf parsing we could reuse (though I have no idea how long it takes, it could be a hit if done on every request).

**Comment by dontcallmedom** [comment]
indeed, specref has https://github.com/tobie/specref/blob/master/scripts/rdf.js

I think I might shamelessly steal it for now; we'll DRY it later.

**Comment by dontcallmedom** [comment]
I think we're good for that issue now with https://github.com/w3c/spec-generator/pull/4
